/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef FLECS_EXPLORER_BAKE_CONFIG_H
#define FLECS_EXPLORER_BAKE_CONFIG_H

/* Headers of public dependencies */
#include "../../deps/flecs.h"
#include "../../deps/flecs_components_transform.h"
#include "../../deps/flecs_components_graphics.h"
#include "../../deps/flecs_components_geometry.h"
#include "../../deps/flecs_components_physics.h"
#include "../../deps/flecs_components_gui.h"
#include "../../deps/flecs_systems_physics.h"
#include "../../deps/flecs_systems_transform.h"
#include "../../deps/flecs_systems_sokol.h"
#include "../../deps/flecs_game.h"

#endif

